language: swift
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilE3Kit.xcodeproj
    - IOS_FRAMEWORK_SCHEME="VirgilE3Kit iOS"
    - MACOS_FRAMEWORK_SCHEME="VirgilE3Kit macOS"
    - TVOS_FRAMEWORK_SCHEME="VirgilE3Kit tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="VirgilE3Kit watchOS"
    - IOS_TEST_SCHEME="E3Kit TestApp iOS"
    - TVOS_TEST_SCHEME="E3Kit TestApp tvOS"
    - MACOS_TEST_SCHEME="E3Kit TestApp macOS"
    - IOS_SDK=iphonesimulator12.0
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.0
    - WATCHOS_SDK=watchsimulator5.0
    - FRAMEWORK_NAME=VirgilSDKKeyknox

  matrix:
    - DESTINATION="OS=12.0,name=iPhone SE"            SCHEME="$IOS_FRAMEWORK_SCHEME"        SDK="$IOS_SDK"        TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="iOS"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$IOS_TEST_SCHEME"        PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="arch=x86_64"                       SCHEME="$MACOS_FRAMEWORK_SCHEME"      SDK="$MACOS_SDK"      TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="Mac"        RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$MACOS_TEST_SCHEME"        PUBLISH_CARTHAGE="YES"    POD_LIB_LINT="NO"    SWIFT_LINT="NO"
    - DESTINATION="OS=12.0,name=Apple TV 4K"          SCHEME="$TVOS_FRAMEWORK_SCHEME"       SDK="$TVOS_SDK"       TWO_STEP_BUILD_ENABLED="YES"    CARTHAGE_PLATFORM_NAME="tvOS"       RUN_TESTS="YES"    ADDITIONAL_TESTS_SCHEME="$TVOS_TEST_SCHEME"        PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="NO"    SWIFT_LINT="YES"
    - DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm"    SCHEME="$WATCHOS_FRAMEWORK_SCHEME"    SDK="$WATCHOS_SDK"    TWO_STEP_BUILD_ENABLED="NO"     CARTHAGE_PLATFORM_NAME="watchOS"    RUN_TESTS="NO"     ADDITIONAL_TESTS_SCHEME=""        PUBLISH_CARTHAGE="NO"     POD_LIB_LINT="YES"   SWIFT_LINT="NO"

before_install:
  - openssl aes-256-cbc -K $encrypted_a7b6c41d0d44_key -iv $encrypted_a7b6c41d0d44_iv -in TestConfig.plist.enc -out TestConfig.plist -d
  - set -e
  - set -o pipefail
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  - mkdir Tests/Data
  - mv -f TestConfig.plist Tests/Data/TestConfig.plist

  - carthage version
  - carthage bootstrap --no-build

  - |
    if [ $SWIFT_LINT == "YES" ]; then
      brew outdated swiftlint || brew upgrade swiftlint
      swiftlint
    fi
  
  - |
    if [ $TWO_STEP_BUILD_ENABLED == "YES" ]; then
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
      # Build Framework in Release and Run Tests if specified
      if [ $RUN_TESTS == "YES" ]; then
        if [ -n "$ADDITIONAL_TESTS_SCHEME" ]; then
          xcodebuild -verbose -project "$PROJECT" -scheme "$ADDITIONAL_TESTS_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test;
        else
          xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean test;
        fi
      fi
    else
      # Build Framework
      xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
    fi

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current --no-use-binaries;
    fi

before_deploy:
  - carthage archive

deploy:
  # Upload framework to gh-releases for carthage
  - provider: releases
    api_key:
      secure: NFnbrxG85CsUuRQoxjjs8+HVhg4gdD6ic/4EtkfiwaM72QB/l9dsORWGytBitbZROn6Rv8mX0rH/iqt7cYtejNKUianrYg/S6CBRY9U0S2yYgVzAeITOex14A+lITpQBZMhir/17h3KVRIe77uuQ2g4L7d9AlTz7mKhl9mXZy7Ru9aS7m8fdqsgTGPMJADRk0yIYTHMLLyYDJiIGEJtGBOTEQRFSYFN7eYYklTYsdcWg40I3gG0SODhp4d6gwoo07XPX8Rv/nNhescvMH741J+/xbTIe1pG1cZHcPzXklwoeZu0tXRSDhGXV+JTj+Q9mxKqYZJ40aXKM1n/N/lM/4QVNyfWfG8hBuSd2plvNLblRkxp+rwTJbEqapY41b1zgW6a8xh5d7F8TWLuekN1LAIxcHm3dS1G0Ue0ZiP139FdyZvOHXKsZzTjHn58Aq9BAiOtkIDdKvz9mPTiSBYrSj2utGzN/PHIxHbw9JDHKd5PizmbMwi6xcQ4XJDCn1I9VYVIyL/fYQov/re/gtZpSF8dOfUxbAsBki/+Jao4RjZiOIfgkoUtNG7KM0u1pBiGO56LOHXo5gqGoLfRVm5QiqhHR6H70yodDlwv/X5BRqCmm3/ed3e7UAjb91NlZzujKwU6ICaS6T3x9wkWFRBmK3OVHm5o7X6K6VzgZIAJrD0c=
    file: $FRAMEWORK_NAME.framework.zip
    skip_cleanup: true
    on:
      repo: VirgilSecurity/e3kit-x
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"
